service: pxsearch

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  environment:
    POSTGRES_HOST: ${file(./secretsHandler.js):getParameters.POSTGRES_HOST}
    POSGRES_PORT: "5432"
    POSTGRES_DBNAME: ${file(./secretsHandler.js):getParameters.POSTGRES_DBNAME}
    POSTGRES_USER: ${file(./secretsHandler.js):getParameters.POSTGRES_USER}
    POSTGRES_PASS: ${file(./secretsHandler.js):getParameters.POSTGRES_PASS}
    SENTRY_DSN: ${file(./secretsHandler.js):getParameters.SENTRY_DSN}

package:
  patterns: pxsearch

functions:
  pxsearch:	
    name: pxsearch
    handler: "pxsearch.ingest.signals.signal_handler"
    events:	
      - externalSNS: "arn:aws:sns:us-west-2:673253540267:public-c2-notify"
      - externalSNS: "arn:aws:sns:us-west-2:608149789419:cirrus-v0-publish"

plugins:
  - serverless-python-requirements
  - serverless-plugin-external-sns-events
