name: Continuous Integration for PxSearch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sure:
        description: 'Are you sure to deploy this thing to production?'
        required: true
        default: 'Not really'

jobs:
  python_dependencies:
    name: Python dependencies
    runs-on: ubuntu-latest
    steps:
     - name: Checkout pxsearch
       uses: actions/checkout@v2
       with:
         path: ./pxsearch
     - name: Attempt to use cache
       uses: actions/cache@v2
       id: cache
       with:
         path: ./pxsearch-venv
         key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
     - name: Install Python 3
       uses: actions/setup-python@v1
       with:
         python-version: 3.8
     - name: Create virtualenv and install deps
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
         python -m pip install --upgrade pip virtualenv
         virtualenv -p /usr/bin/python3 ./pxsearch-venv
         source ./pxsearch-venv/bin/activate
         pip install setuptools==57.5.0
         pip install -r ./pxsearch/requirements.txt

  deploy-staging:
    name: Deploy to Staging
    needs: [python_dependencies]
    runs-on: ubuntu-latest
    if: contains('refs/heads/main', github.ref)
    steps:
      - name: Checkout pxsearch
        uses: actions/checkout@v2
        with:
          path: ./pxsearch
      - name: Attempt to use cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ./pxsearch-venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
      - name: Deploy
        run: |
          source ./pxsearch-venv/bin/activate
          cd ./pxsearch
          zappa update staging --disable_progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-production:
    name: Deploy to Production
    needs: [python_dependencies]
    runs-on: ubuntu-latest
    if: contains('yes', github.event.inputs.sure) && contains('workflow_dispatch', github.event_name)
    steps:
      - name: Checkout pxsearch
        uses: actions/checkout@v2
        with:
          path: ./pxsearch
      - name: Attempt to use cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ./pxsearch-venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
      - name: Deploy
        run: |
          source ./pxsearch-venv/bin/activate
          cd ./pxsearch
          zappa update production --disable_progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
